### ISSUE TITLE
Run `feature.shutdown()` before unloading the JSM file

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/taar-experiment-v3-shield-study#11]
I filed this issue here: mozilla/shield-studies-addon-template#44.

Depending on what you're doing during shutdown, the procedure might be failing because the dependencies are getting unloaded before the `shutdown` method gets called, see [here](https://github.com/motin/taar-experiment-v2-shield-study/blob/ecaf422e399199ac2b649bf9f61bb6861d45d0e5/addon/bootstrap.js#L137-L141).

This is potentially not being trigger as the shutdown procedure might not be called at all due to [this](https://github.com/motin/taar-experiment-v2-shield-study/blob/ecaf422e399199ac2b649bf9f61bb6861d45d0e5/addon/bootstrap.js#L131).

**Comment by motin** [comment]
Thanks, this has been addressed in 09d17fc835e5969d273ecc8ef02afb0224ea181c and d5ebdee86eba08cf9a55970ed5d573bbd62d8391
