### ISSUE TITLE
jigsaw toolbar button lingers after new tab 

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar-experiment-v3-shield-study#13]
More detailed description of the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1435238

If a client triggers the 'explore addons' pop-up dialog and then opens a new tab but does NOT navigate to a new URI, the jigsaw button lingers.

this is a low priority fix due to the unusual edge case required to reproduce, and the relatively harmless effect on client experience when triggered. Nonetheless, a more elegant behavior could be implemented.

--m

**Comment by motin** [comment]
Closed as won'tfix
