### ISSUE TITLE
The popup logic needs to be refined to avoid bugs from the previous experiment

### ISSUE THREAD

**Issue by motin** [mozilla/taar-experiment-v3-shield-study#2]
@benmiroglio can you supply the link to the bug report regarding the inability to close the popup for some users? It is not listed in https://github.com/benmiroglio/taar-experiment/issues - Btw related: https://stackoverflow.com/questions/38577570/why-wont-firefox-add-on-browser-action-pop-up-close

**Comment by benmiroglio** [comment]
There isn't a bug for this issue as we couldn't reproduce it. We only discovered that some users were affected from this reddit thread: https://www.reddit.com/r/firefox/comments/742gg7/is_there_any_way_to_turn_off_the_customize/

**Comment by motin** [comment]
The v2 extension is now using a study-persistent client status preference instead of local storage to track total web navigations so that they reflect the number of web navigations during the study period and not since last local storage reset. This should ensure that the popup logic is only shown once during the study period.
