### ISSUE TITLE
PHD document in README.md is not set to public visibility

### ISSUE THREAD

**Issue by tdaede** [mozilla/taar-experiment-v3-shield-study#23]
The document has a rather nice high-level description that's otherwise missing from the README.

**Comment by mlopatka** [comment]
@tdaede This document is for **internal** review of the study methodology and discussions pertaining to the study structure. It is not intended for public visibility outside Mozilla as this may bias the behavior of study participants but also generate substantial noise for the already over-burdened study review team. 

A summary of the PHD can be transcribed into the README.md but managing public visibility permissions on our internal document store quickly becomes a security hazard.
