### ISSUE TITLE
Diagnose source of "other" category installation sources.

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar-experiment-v3-shield-study#25]
it looks like:

`static bucketURI(uri) {
   if (uri !== "about:addons") {
     if (uri.indexOf("addons.mozilla.org") > 0) {
       uri = "AMO";
     } else {
       uri = "other";
     }
   }
   return uri;
 }
`

returning far too many "other" results to be edge cases. Can we do something to make the other conditions more robust?

**Comment by motin** [comment]
Quick update: I put the bucketURI method under [more scrutiny](https://github.com/motin/taar-experiment-v3-shield-study/blob/develop/test/unit_tests.js#L127-L187) and found no apparent coding issue / bug.

**Comment by motin** [comment]
Closing the issue since we have refactored the way of categorizing the bucketURI and unsuccessfully attempted to reproduce behavior for getting "other" when navigating away from AMO/about:addons right after/during accepting the add-on to be installed.

**Comment by motin** [comment]
@mlopatka, I noticed that some automatic/maintenance add-on change activity was happening during "about:blank" so I left it as it's own bucket.
