### ISSUE TITLE
Add add-on description for about:addons listing

### ISSUE THREAD

**Issue by motin** [mozilla/taar-experiment-v3-shield-study#26]
@mlopatka Could you provide the copy? I'll add it to the manifest.

**Comment by mlopatka** [comment]
please use the following copy in the Extension description:

> The TAAR v3 (Telemetry-Aware Addon Recommender) extension is automatically installed by Mozilla to help us evaluate prototype improvements to the about:addons user experience. To change your study enrollment preferences please navigate to about:studies. More information about the TAAR project can be found at https://github.com/mozilla/taar
