### ISSUE TITLE
Be able to detect if user went to disco pane, was loaded and left the pane without installing an add-on

### ISSUE THREAD

**Issue by motin** [mozilla/taar-experiment-v3-shield-study#3]

**Comment by motin** [comment]
The extension now tracks if the disco pane was loaded. Tracking if the user left the pane requires a more concise definition of what it means to leave the disco pane.

**Comment by motin** [comment]
@mlopatka How do we define "left the pane"?

= Manually closed it?
or
= Did not interact* with it? Within a certain time frame?
or
= Navigated away from the tab where disco pane was opened? Despite coming back later?
or
= Something else?

* Note that we can't instrument interaction until [Hybrid Content Telemetry](https://bugzilla.mozilla.org/show_bug.cgi?id=1417473) is in place, earliest in fx 58-59.

**Comment by mlopatka** [comment]
As per discussion on 08-01-2018, this definition will be left for the analysis stage. Interim instrumentation is to keep track of cumulative seconds during which about:addons is the active tab and report that quantity opportunistically in next possible ping.

**Comment by motin** [comment]
Fixed in https://github.com/motin/taar-experiment-v2-shield-study/commit/0f4ab004a037f4326dfc74dc646cbf7d46390e05
