### ISSUE TITLE
Change Firefox icon in doorhanger to puzzle piece icon

### ISSUE THREAD

**Issue by pwalm** [mozilla/taar-experiment-v3-shield-study#30]
Was alerted that we're using the wrong icon in the door hanger, as seen here:
<img width="673" alt="screen shot 2018-06-28 at 9 34 04 am" src="https://user-images.githubusercontent.com/6797635/42050136-fb29b87e-7abc-11e8-8059-a92080f3d490.png">

It needs to be changed to the puzzle piece icon. png is attached to this issue.
[addonicon.zip](https://github.com/motin/taar-experiment-v3-shield-study/files/2146259/addonicon.zip)

**Comment by sevaan** [comment]
We should probably use the SVG for this. 

[extensionsicon.svg.zip](https://github.com/motin/taar-experiment-v3-shield-study/files/2146288/extensionsicon.svg.zip)

#0c0c0d
