### ISSUE TITLE
The "TAAR" shield study is not removed after its expiration date

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/taar-experiment-v3-shield-study#40]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546) installed.
- Create the following prefs in the "about:config" page:
	- "shieldStudy.logLevel" as string and set it to "All";
	- "extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to three websites and click the doorhanger's "Browse Add-ons" button.
3. Change the OS system time to more than 7 weeks in the future (e.g. 10/31/2018).
4. Restart the browser and go to "about:addons>Extensions".
5. Look after the "TAAR v3" add-on.

**[Expected result]:**
- The "TAAR" add-on is no longer displayed.

**[Actual result]:**
- The "TAAR" add-on is still displayed.

**[Notes]:**
- On similar shield studies, the add-on is removed from the "about:addons" page after its expiration.

**Comment by motin** [comment]
@Softvision-MariusComan: The current expiration is configured to be [20 weeks](https://github.com/motin/taar-experiment-v3-shield-study/blob/develop/src/studySetup.js#L68), could you re-test and check if it works if you set the date more than 20 weeks into the future? Thanks

**Comment by Softvision-MariusComan** [comment]
@motin I have changed the system date to more than 20 weeks into the future and the "TAAR" experiment expires. Also, the study is no longer displayed in "about:addons" page and the "expires" pings are correctly sent.
However, according to the [PHD](https://docs.google.com/document/d/1r8RC8BBjS9DQSBfanlD-MlCS4XWN3-bozyWOIFlD8aA/edit), the study should not be live only for 7 weeks?

**Comment by motin** [comment]
@Softvision-MariusComan We'll go with 7 weeks expiration for this specific study. It has been set to 7 weeks in v3.0.2

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "TAAR v3" add-on (3.0.2) installed on latest Firefox release (61.0.1) and latest Firefox Beta (62.0b7). Verified on Windows 10 x64, Mac 10.13 and Arch Linux. 
Considering the above I am closing this issue.
