### ISSUE TITLE
The "sawPopup" attribute's value is "false" instead of "true" after the doorhanger is displayed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/taar-experiment-v3-shield-study#42]
[Affected versions]:
- Firefox 61.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546) installed.
- Create the following prefs in the "about:config" page:
"shieldStudy.logLevel" as string and set it to "All";
"extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website (https://www.wikipedia.org/).
2. Click 3 different links (one after another) from the website's content (without leaving the current active tab).
3. Navigate to the "about:telemetry" page and select the "Archived ping data" ("shield-study-addon" ping type).
4. Click the "Raw JSON" button.
5. Observe the value of the "sawPopup" attribute.

[Expected result]:
- The value is "true".

[Actual results]:
- The value is "false".

[Notes]:
- This issue is also reproducible if you click the "Close" button, dismiss the doorhanger or click anywhere inside it.
- This issue is not reproducible with TAAR 3.0.1 version.
- Here is a screen recording with the issue:
![taar 3 - saw pop up](https://user-images.githubusercontent.com/31244235/42514930-38e47be0-8463-11e8-9e41-fccc8ce4147c.gif)

**Comment by motin** [comment]
This is a clear regression that was introduced in the fix for https://github.com/motin/taar-experiment-v3-shield-study/issues/28 - Thanks for catching this!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "TAAR v3" add-on (3.0.3) installed on latest Firefox release (61.0.1) and latest Firefox Beta (62.0b7). Verified on Windows 10 x64, Mac 10.13 and Arch Linux.
Considering the above I am closing this issue.
