### ISSUE TITLE
A couple of ESLint errors in /addon/lib/Feature.jsm

### ISSUE THREAD

**Issue by pdehaan** [mozilla/taar-experiment-v3-shield-study#5]
```sh
$ git rev-parse head # 40c7b8b4b14b0b793737da1507efc64634123556
```

### Steps to reproduce

1. `npm run eslint`

### Actual results:

```
/Users/pdehaan/dev/github/mozilla/taar-experiment-v2-shield-study/addon/lib/Feature.jsm
  113:7  error  'featureInstance' is not defined                             no-undef
  125:5  error  Static method 'getNonSystemAddons' expected no return value  consistent-return
```

https://github.com/motin/taar-experiment-v2-shield-study/blob/40c7b8b4b14b0b793737da1507efc64634123556/addon/lib/Feature.jsm#L109-L115

**NOTE:** On line 113, 'featureInstance' is not defined.

---

https://github.com/motin/taar-experiment-v2-shield-study/blob/40c7b8b4b14b0b793737da1507efc64634123556/addon/lib/Feature.jsm#L109-L126

**NOTE:** The static `getNonSystemAddons()` method either returns undefined/null (see line 114), or a `Set()` instance (see line 125).

**Comment by motin** [comment]
Thank you for the report :) Fixed in https://github.com/motin/taar-experiment-v2-shield-study/commit/66a111d2385004763a7fa611d68a350740571f22 and https://github.com/motin/taar-experiment-v2-shield-study/commit/2aa63386899b7972ed8d99950f406b9a73eaa458
